# Site settings
baseurl = "/"
languageCode = "en-us"
title = "Okkur - Syna"
theme = "syna"
themesDir = "../.."
copyright = "" # default: Copyright $Year $params.name

# Google Analytics tracking
googleAnalytics = ""

[params]
  name = "Okkur Labs"
  description = "Open Source Theme for your next project"
  attribution = "true"

  # Branding options
  [params.branding]
    logoNavigation = "logo.svg"
    textNavigation = "Syna"

  [params.style]
    #background = "secondary"
    #backgroundNavigation = "light" # white, light, secondary, primary, dark - default: dark
    #backgroundFooter = "light" # white, light, secondary, primary, dark - default: dark

  # Theme customizations
  # Assets relative to 'static/'
  [params.custom]
    favicon = "favicon.ico"
    faviconICOSizes = "16x16 32x32"
    faviconPNG = "favicon.png"
    faviconSVG = "favicon.svg"
    css = ["css/overwrite-color.min.css", "css/overwrite-reboot.min.css"]
    js  = []

  # Repository Button
  [params.repoButton]
    url = "https://github.com/okkur/syna"
    text = "Star" # default: "Star"
    icon = "fa-github" # defaults: "fa-github"

  # Piwik tracking
  [params.analytics.piwik]
    url = "https://stats.example.com"
    id = "42"
    domain = "www.example.com" # Track subdomains via "*.example.com"
    # Optional hash for integrity check
    #hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

  # Optional, global disable switch for form related files
  [params.contact]
    disabled = false

  # Optional, global disable switch for fontawesome related files
  # For custom fontawesome js files use the custom.js method
  [params.fontawesome]
    disabled = false

  # Optional google captcha
  #[params.contact.captcha]
  #  sitekey = ""

[[menu.main]]
  url = "#"
  name = "Long Link"
  weight = 10

[[menu.main]]
  url = "/about-split"
  name = "Page-split"
  weight = 30

[[menu.main]]
  url = "/about"
  name = "Page-single"
  weight = 30

[[menu.main]]
  url = "#contact-fragment"
  name = "Contact"
  weight = 50

[[menu.main]]
  url = "#"
  name = "Link"
  weight = 30

[[menu.legalFooter]]
  url = "/about"
  name = "About Us"
  weight = 10

[[menu.legalFooter]]
  url = "#"
  name = "Another Link"
  weight = 30

[[menu.footer]]
  url = "#"
  name = "Link"
  weight = 10

[[menu.footer]]
  url = "#"
  name = "Long Link"
  weight = 30

[[menu.footer]]
  url = "#"
  name = "Tiny Link"
  weight = 30

[[menu.footerSocial]]
  weight = 20
  name = "facebook"
  pre = "fa-facebook-f"
  url = "#"

[[menu.footerSocial]]
  weight = 30
  name = "linkedin"
  pre = "fa-linkedin-in"
  url = "#"
